#!/usr/bin/env bash
#
# Deploy the General Store on a Serv00.com free account.
#
# Serv00 is free forever — no credit card, no ads, no expiry, no spin-down.
# Data lives on persistent SSD (daily backups), so the SQLite database
# survives restarts. This script assumes you are already SSH'd into your
# Serv00 account as a normal (non-root) user and the repo is cloned.
#
# Before running (see deploy/serv00/CHECKLIST.md for the full walkthrough):
#   1. Register at https://www.serv00.com and wait for activation.
#   2. SSH in using the host/port shown in your DevilWEB panel.
#   3. Clone this repo, e.g.:  git clone https://github.com/steamytooolz-commits/general-store.git ~/apps/general-store
#   4. Run one command:  bash deploy/serv00/setup-serv00.sh
#
# The script auto-picks a free TCP port from your account's allocations
# (override with PORT=1234), finds a Node 22 binary (node22) or installs one
# in ~/.node22, starts the store with nohup, and registers a @reboot cron
# entry so it comes back after server restarts.

set -euo pipefail

APP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
LOG_DIR="$APP_DIR/logs"
DB_DIR="$APP_DIR/data"

echo "==> General Store bootstrap on $(hostname)"
echo "    app dir: $APP_DIR"

if [ ! -f "$APP_DIR/package.json" ] || [ ! -d "$APP_DIR/src" ]; then
  echo "error: no General Store checkout found at $APP_DIR" >&2
  echo "hint:  git clone https://github.com/steamytooolz-commits/general-store.git $APP_DIR" >&2
  exit 1
fi

# ---- 1. Find (or install) Node 22 -----------------------------------------
NODE_BIN=""
if [ -x "$HOME/.node22/bin/node" ]; then
  NODE_BIN="$HOME/.node22/bin/node"
elif command -v node22 >/dev/null 2>&1; then
  NODE_BIN="$(command -v node22)"
elif command -v node >/dev/null 2>&1; then
  NODE_BIN="$(command -v node)"
fi

if [ -n "$NODE_BIN" ] && [ "$("$NODE_BIN" -e 'console.log(process.versions.node.split(".")[0])' 2>/dev/null || echo 0)" -lt 22 ]; then
  echo "==> Node at $NODE_BIN is too old, installing Node 22 in ~/.node22 …"
  NODE_BIN=""
fi

if [ -z "$NODE_BIN" ]; then
  echo "==> Installing Node 22 (userland, no root needed) …"
  mkdir -p "$HOME/.node22" "$HOME/.cache/node-dl"
  curl -fsSL -o "$HOME/.cache/node-dl/node22.tar.xz" \
    https://nodejs.org/dist/latest-v22.x/$(curl -fsSL https://nodejs.org/dist/latest-v22.x/ | grep -oE 'node-v22\.[0-9]+\.[0-9]+-linux-x64\.tar\.xz' | head -1)
  tar -xJf "$HOME/.cache/node-dl/node22.tar.xz" -C "$HOME/.node22" --strip-components=1
  NODE_BIN="$HOME/.node22/bin/node"
fi

echo "==> Using Node $("$NODE_BIN" --version) at $NODE_BIN"
"$NODE_BIN" -e 'require("node:sqlite")' 2>/dev/null || {
  echo "error: this Node build lacks node:sqlite — need Node >= 22.5" >&2
  exit 1
}

# ---- 1b. Pick a free TCP port ------------------------------------------------
# Prefer an allocated port from the account (devil tool), else a common default.
pick_port() {
  local candidates=() line tok p
  if command -v devil >/dev/null 2>&1; then
    while read -r line; do
      for tok in $line; do
        if [[ "$tok" =~ ^[0-9]{2,5}$ ]]; then candidates+=("$tok"); fi
      done
    done < <(devil port list 2>/dev/null || true)
  fi
  candidates+=(3000 8080 8000 43210)
  for p in "${candidates[@]}"; do
    if "$NODE_BIN" -e "const s=require('net').createServer();s.once('error',()=>process.exit(1));s.listen($p,'127.0.0.1',()=>s.close(()=>process.exit(0)))" 2>/dev/null; then
      echo "$p"
      return 0
    fi
  done
  echo 3000
}

PORT="${PORT:-$(pick_port)}"
echo "    port:    $PORT (override with PORT=<n> if needed)"

# ---- 2. Data + log dirs ----------------------------------------------------
mkdir -p "$LOG_DIR" "$DB_DIR"
export DB_PATH="$DB_DIR/store.db"

# ---- 3. Start script (used now and by cron on reboot) ----------------------
START_SH="$APP_DIR/start.sh"
cat > "$START_SH" <<EOF
#!/usr/bin/env bash
# Auto-generated by deploy/serv00/setup-serv00.sh
cd "$APP_DIR"
pkill -f "src/server.js" 2>/dev/null || true
sleep 1
export PORT=$PORT
export DB_PATH=$DB_DIR/store.db
nohup "$NODE_BIN" --experimental-sqlite src/server.js >> "$LOG_DIR/store.log" 2>&1 &
echo \$! > "$APP_DIR/.pid"
EOF
chmod +x "$START_SH"

# ---- 4. Register @reboot cron so it survives server restarts ---------------
CRON_LINE="@reboot $START_SH"
if crontab -l 2>/dev/null | grep -qF "general-store/start.sh"; then
  echo "==> Cron entry already present"
else
  (crontab -l 2>/dev/null | grep -vF "general-store/start.sh"; echo "$CRON_LINE") | crontab -
  echo "==> Added cron: $CRON_LINE"
fi

# ---- 5. Start now -----------------------------------------------------------
"$START_SH"
sleep 2
PID="$(cat "$APP_DIR/.pid" 2>/dev/null || echo unknown)"
if kill -0 "$PID" 2>/dev/null; then
  echo "==> Store is running (pid $PID)"
else
  echo "==> WARNING: process not running — last log lines:"
  tail -n 20 "$LOG_DIR/store.log" 2>/dev/null || true
fi

echo
echo "─── Next steps ──────────────────────────────────────────────────────"
echo "  • Local check:    curl -s http://127.0.0.1:$PORT/api/products"
echo "  • Public address: use the hostname Serv00 assigned to your TCP port"
echo "                    (see DevilWEB panel), e.g. http://<user>.serv00.net:$PORT"
echo "  • Logs:           tail -f $LOG_DIR/store.log"
echo "  • Restart:        $START_SH"
echo "  • Update app:     cd $APP_DIR && git pull && $START_SH"
echo "  • Optional: map a free subdomain + Let's Encrypt via DevilWEB for a"
echo "    clean https:// URL (no port in the address)."
echo "──────────────────────────────────────────────────────────────────────"
echo
tail -n 3 "$LOG_DIR/store.log" 2>/dev/null || true